JavaProgrammingContest.Web/Controllers/AssignmentController.cs
using System.Linq;
using System.Web.Mvc;
using JavaProgrammingContest.DataAccess.Context;
using JavaProgrammingContest.Domain.Entities;

namespace JavaProgrammingContest.Web.Controllers{
    /// <summary>
    ///     Assignment Administration Controller
    /// </summary>
    [Authorize(Roles = "Administrator")]
    public class AssignmentController : Controller{
        /// <summary>
        ///     Database Context
        /// </summary>
        private readonly IDbContext _db;

        /// <summary>
        ///     Controller Constructor
        /// </summary>
        /// <param name="context"></param>
        public AssignmentController(IDbContext context){
            _db = context;
        }

        /// <summary>
        ///     GET: /Assignment/
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(){
            return View(_db.Assignments.ToList());
        }

        /// <summary>
        ///     GET: /Assignment/Details/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id = 0){
            Assignment assignment = _db.Assignments.Find(id);
            if (assignment == null)
                return HttpNotFound();
            return View(assignment);
        }

        /// <summary>
        ///     GET: /Assignment/Create
        /// </summary>
        /// <returns></returns>
        public ActionResult Create(){
            return View();
        }

        /// <summary>
        ///     POST: /Assignment/Create
        /// </summary>
        /// <param name="assignment"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Assignment assignment){
            if (ModelState.IsValid){
                _db.Assignments.Add(assignment);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(assignment);
        }

        /// <summary>
        ///     GET: /Assignment/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id = 0){
            Assignment assignment = _db.Assignments.Find(id);
            if (assignment == null)
                return HttpNotFound();
            return View(assignment);
        }

        /// <summary>
        ///     POST: /Assignment/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <param name="assignment"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(int id, Assignment assignment){
            if (ModelState.IsValid){
                var assignmentOld = _db.Assignments.Find(id);

                if (TryUpdateModel(assignmentOld)){
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("Internal Error", "Unexpected error while saving to the database.");
            }
            return View(assignment);
        }

        /// <summary>
        ///     GET: /Assignment/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id = 0){
            Assignment assignment = _db.Assignments.Find(id);
            if (assignment == null)
                return HttpNotFound();
            return View(assignment);
        }

        /// <summary>
        ///     POST: /Assignment/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id){
            Assignment assignment = _db.Assignments.Find(id);
            _db.Assignments.Remove(assignment);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

JavaProgrammingContest.Web/Controllers/EditorController.cs
using System.Web.Mvc;

namespace JavaProgrammingContest.Web.Controllers{
    /// <summary>
    ///     Controller for the Editor.
    /// </summary>
    [Authorize]
    public class EditorController : Controller{
        /// <summary>
        ///     Creates the view for the editor.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(){
            return View();
        }
    }
}

JavaProgrammingContest.Web/Controllers/ScoresController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Web.Mvc;
using JavaProgrammingContest.DataAccess.Context;
using JavaProgrammingContest.Domain.Entities;

namespace JavaProgrammingContest.Web.Controllers{
    /// <summary>
    ///     Scoreboard controller.
    /// </summary>
    public class ScoresController : Controller{
        /// <summary>
        ///     Database Context
        /// </summary>
        private readonly IDbContext _context;

        /// <summary>
        ///    Scores controller constructor
        /// </summary>
        /// <param name="context">Database Context to use for the Controller</param>
        public ScoresController(IDbContext context){
            _context = context;
        }

        /// <summary>
        ///     Index for this Controller
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(new Leaderboard(_context.Contests, _context.Participants));
        }
    }

    public class Leaderboard
    {
        public IEnumerable<ContestScore> Contest { get; set; }
        private readonly IDbSet<Contest> _contestsSet;
        private readonly IDbSet<Participant> _participantSet;

        public Leaderboard(IDbSet<Contest> contestsSet, IDbSet<Participant> participantList)
        {
            _contestsSet = contestsSet;
            _participantSet = participantList;
            CreateLeaderboard();
        }

        private void CreateLeaderboard()
        {
            var contestScores = new List<ContestScore>();

            if (_contestsSet != null)
                foreach (var contest in _contestsSet)
                    if (contest.Assignments != null)
                        contestScores.Add(new ContestScore(contest, _participantSet));
                

            Contest = contestScores;
        }
    }

    public class ContestScore
    {
        public string ContestName { get; set; }
        public IEnumerable<ParticipantScore> Participants { get; set; }
        private readonly Contest _contest;
        private IDbSet<Participant> ParticipantList { get; set; }

        public ContestScore(Contest contest, IDbSet<Participant> participantList)
        {
            _contest = contest;
            ContestName = contest.Name;
            ParticipantList = participantList;
            AddParticipantScores();
        }

        private void AddParticipantScores()
        {
            var participantScores = new List<ParticipantScore>();
            var idList = GetUniqueIdList();

            if (idList != null)
                foreach (var id in idList)
                    foreach (var participant in ParticipantList)
                        if (id == participant.Id)
                            participantScores.Add(new ParticipantScore(_contest, participant));

            Participants = participantScores;
        }

        private IEnumerable<int> GetUniqueIdList()
        {
            var idList = new List<int>();

            foreach (var assignment in _contest.Assignments)
                foreach (var score in assignment.Scores)
                {
                    var newId = score.Participant.Id;
                    var idfound = false;

                    foreach (var oldId in idList)
                        if (oldId == newId)
                            idfound = true;

                    if (!idfound)
                        idList.Add(newId);
                }

            return idList;
        }
    }

    public class ParticipantScore
    {
        public string Email { get; set; }
        public string Name { get; set; }
        public string Functie { get; set; }
        public int AssignmentsCompleted { get; set; }
        public int AssignmentsMade { get; set; }
        public double AverageTime { get; set; }
        public double CompletePercentage { get; set; }

        public ParticipantScore(Contest contest, Participant participant)
        {
            Email = participant.Email;
            Name = participant.Name;
            Functie = participant.Functie;
            SetScore(contest, participant.Id);
        }

        private void SetScore(Contest contest, int id)
        {
            var assignmentsMade = 0;
            var assignmentsCompleted = 0;
            var totalTime = 0.0;

            foreach (var assignment in contest.Assignments)
                foreach (var score in assignment.Scores)
                    if (id == score.Participant.Id)
                    {
                        assignmentsMade++;
                        totalTime += score.TimeSpent;
                        if (score.IsCorrectOutput)
                            assignmentsCompleted++;
                    }

            AssignmentsMade = assignmentsMade;
            AssignmentsCompleted = assignmentsCompleted;
            AverageTime = totalTime / assignmentsMade + 0.0;
            CompletePercentage = CalculateCompletePercentage(assignmentsMade, assignmentsCompleted);
        }

        private static double CalculateCompletePercentage(int assignmentsMade, int assignmentsComplete)
        {
            double completePercentage = 0.0;
            double made = assignmentsMade;
            double complete = assignmentsComplete;

            if (assignmentsComplete != 0 && assignmentsMade != 0)
            {
                completePercentage = (complete / made) * 100;
            }

            return completePercentage;
        }
    }
}

JavaProgrammingContest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - InfoSupport Programmeer Wedstrijd</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
     <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
</head>
<body>
       @*@Html.Partial("_LoginPartial")*@
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <!--a class="brand" href="@Url.Action("Index", "Home")">Programmeerwedstrijd</a-->
                <a class="brand" href="@Url.Action("Index", "Home")"><img src="/Content/images/is_logo.png" alt="InfoSupport Contest"/></a>
          
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Opdrachten", "Index", "Editor")</li>
                        <li>@Html.ActionLink("Scorebord", "Index", "Scores")</li>
                        <li>@Html.ActionLink("Over Ons", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                         @if (User.IsInRole("Administrator"))
                         {
                             <li>@Html.ActionLink("Beheren", "Index", "Assignment")</li>
                         }
                    </ul>
                </div>
                <!--/.nav-collapse -->    
                  @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    
    @if (IsSectionDefined("editor-row"))
    {
        <div class="container-fluid">
            @RenderBody()
        </div>
    }
    else
    {
        <div class="container">
        @RenderBody()
    </div>
    }
       
    
    @Scripts.Render("~/Script/Bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>